---
  version: "2.1"
  services:
    qbittorrent:
      image: ghcr.io/linuxserver/qbittorrent
      container_name: qbittorrent
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - WEBUI_PORT=8080
      volumes:
        - ./config/qbittorrent:/config
        - /storage/downloads:/downloads
      ports:
        - 6881:6881
        - 6881:6881/udp
        - 8080:8080
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.qbittorrent.rule=PathPrefix(`/qbittorrent`)"

    radarr:
      image: ghcr.io/linuxserver/radarr
      container_name: radarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - ./config/radarr:/config
        - /storage/movies:/movies
        - /storage/downloads:/downloads
      ports:
        - 7878:7878
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.radarr.rule=PathPrefix(`/radarr`)"

    sonarr:
      image: ghcr.io/linuxserver/sonarr
      container_name: sonarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - ./config/sonarr:/config
        - /storage/tv:/tv
        - /storage/downloads:/downloads
      ports:
        - 8989:8989
      restart: unless-stopped
    jackett:
      image: ghcr.io/linuxserver/jackett
      container_name: jackett
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - AUTO_UPDATE=true
      volumes:
        - ./config/jackett:/config
        - /storage/downloads:/downloads
      ports:
        - 9117:9117
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sonarr.rule=PathPrefix(`/sonarr`)"

    bazarr:
      image: ghcr.io/linuxserver/bazarr
      container_name: bazarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - ./config/bazarr:/config
        - /storage/movies:/movies
        - /storage/tv:/tv
      ports:
        - 6767:6767
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bazarr.rule=PathPrefix(`/bazarr`)"

    traefik:
      image: "traefik:v2.4"
      container_name: "traefik"
      command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
      ports:
        - "80:80"
        # - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"