---
  version: "2.1"
  services:
    qbittorrent:
      image: ghcr.io/linuxserver/qbittorrent
      container_name: qbittorrent
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - WEBUI_PORT=8080
      volumes:
        - ./config/qbittorrent:/config
        - ../downloads:/downloads
      ports:
        - 6881:6881
        - 6881:6881/udp
        - 8080:8080
      restart: unless-stopped

    radarr:
      image: ghcr.io/linuxserver/radarr
      container_name: radarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - ./config/radarr:/config
        - ../movies:/movies
        - ../downloads:/downloads
      ports:
        - 7878:7878
      restart: unless-stopped

    sonarr:
      image: ghcr.io/linuxserver/sonarr
      container_name: sonarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - ./config/sonarr:/config
        - ../tv:/tv
        - ../downloads:/downloads
      ports:
        - 8989:8989
      restart: unless-stopped